# Max width of each line
max_width = 100

# Rust community convention: spaces (4) or tab = false for spaces
use_tabs = false
tab_spaces = 4

indent_style = "Block"

struct_field_align_threshold = 20

# Control how comments are formatted
normalize_comments = true
wrap_comments = true
comment_width = 100

# Control formatting of method chains
chain_split_threshold = 80
indent_method_chain = true

# Imports formatting
reorder_imports = true
group_imports = "StdExternalCrate" # separate standard library from external crates
merge_imports = true

# Control trailing commas
trailing_comma = "Always"

# Control alignment of comments and attributes
align_comments = true
align_attributes = true

# How to format single-line vs multi-line
single_argument = "Always"        # put each argument on its own line if multiline
match_block_trailing_comma = true

# Control visibility groups
# (no explicit option in rustfmt to group visibilities, but keep consistent ordering manually)

# Control where to place attributes
reorder_modules = true
format_macro_args = true

# Use the 'visual' indent for nested indentations
visual_indent_width = 4

# Overflow behaviour
overflow_delimited_expr = "Auto"

# Control blank lines
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Use the newer rustfmt rule for where to put braces
brace_style = "AlwaysNextLineWhereRequired"

# Preserve width of chained method calls
wrap_chained_methods = true
